#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeCity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HopecityDB")]
	public partial class hcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQA(QA instance);
    partial void UpdateQA(QA instance);
    partial void DeleteQA(QA instance);
    partial void Insertstudent(student instance);
    partial void Updatestudent(student instance);
    partial void Deletestudent(student instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public hcDataContext() : 
				base(global::HopeCity.Properties.Settings.Default.HopecityDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public hcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QA> QAs
		{
			get
			{
				return this.GetTable<QA>();
			}
		}
		
		public System.Data.Linq.Table<student> students
		{
			get
			{
				return this.GetTable<student>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QA")]
	public partial class QA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<bool> _A1;
		
		private string _A1D;
		
		private System.Nullable<bool> _A2;
		
		private string _A2D;
		
		private string _A3;
		
		private System.Nullable<bool> _A4;
		
		private System.Nullable<bool> _A5;
		
		private string _A5D;
		
		private System.Nullable<bool> _A6;
		
		private System.Nullable<bool> _A7;
		
		private System.Nullable<bool> _A8;
		
		private string _A8D;
		
		private System.Nullable<bool> _A9;
		
		private string _A9D;
		
		private System.Nullable<bool> _A10;
		
		private System.Nullable<bool> _A11;
		
		private System.Nullable<bool> _A12;
		
		private System.Nullable<bool> _A13;
		
		private string _A14;
		
		private System.Nullable<bool> _A15;
		
		private string _A15D;
		
		private System.Nullable<bool> _A16;
		
		private string _A16D;
		
		private System.Nullable<bool> _A17;
		
		private string _A17D;
		
		private System.Nullable<bool> _A18;
		
		private string _A18D;
		
		private System.Nullable<bool> _A19;
		
		private System.Nullable<bool> _A20;
		
		private System.Nullable<bool> _A21;
		
		private string _A21D;
		
		private System.Nullable<bool> _A22;
		
		private string _A22D;
		
		private System.Nullable<bool> _A23;
		
		private string _A23D;
		
		private System.Nullable<bool> _A24;
		
		private string _A24D;
		
		private string _A25;
		
		private System.Nullable<bool> _A26;
		
		private string _A26D;
		
		private string _A27;
		
		private System.Nullable<bool> _A28;
		
		private string _A28D;
		
		private string _A29;
		
		private string _A30;
		
		private string _A31;
		
		private System.Nullable<bool> _A32;
		
		private string _A33;
		
		private string _A34;
		
		private string _A35;
		
		private string _A36;
		
		private System.Nullable<bool> _A37;
		
		private System.Nullable<bool> _A38;
		
		private System.Nullable<bool> _A39;
		
		private string _A39D;
		
		private System.Nullable<bool> _A41;
		
		private string _A42;
		
		private string _A43;
		
		private string _A44;
		
		private string _A45;
		
		private string _A46;
		
		private string _studentId;
		
		private EntityRef<student> _student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnA1Changing(System.Nullable<bool> value);
    partial void OnA1Changed();
    partial void OnA1DChanging(string value);
    partial void OnA1DChanged();
    partial void OnA2Changing(System.Nullable<bool> value);
    partial void OnA2Changed();
    partial void OnA2DChanging(string value);
    partial void OnA2DChanged();
    partial void OnA3Changing(string value);
    partial void OnA3Changed();
    partial void OnA4Changing(System.Nullable<bool> value);
    partial void OnA4Changed();
    partial void OnA5Changing(System.Nullable<bool> value);
    partial void OnA5Changed();
    partial void OnA5DChanging(string value);
    partial void OnA5DChanged();
    partial void OnA6Changing(System.Nullable<bool> value);
    partial void OnA6Changed();
    partial void OnA7Changing(System.Nullable<bool> value);
    partial void OnA7Changed();
    partial void OnA8Changing(System.Nullable<bool> value);
    partial void OnA8Changed();
    partial void OnA8DChanging(string value);
    partial void OnA8DChanged();
    partial void OnA9Changing(System.Nullable<bool> value);
    partial void OnA9Changed();
    partial void OnA9DChanging(string value);
    partial void OnA9DChanged();
    partial void OnA10Changing(System.Nullable<bool> value);
    partial void OnA10Changed();
    partial void OnA11Changing(System.Nullable<bool> value);
    partial void OnA11Changed();
    partial void OnA12Changing(System.Nullable<bool> value);
    partial void OnA12Changed();
    partial void OnA13Changing(System.Nullable<bool> value);
    partial void OnA13Changed();
    partial void OnA14Changing(string value);
    partial void OnA14Changed();
    partial void OnA15Changing(System.Nullable<bool> value);
    partial void OnA15Changed();
    partial void OnA15DChanging(string value);
    partial void OnA15DChanged();
    partial void OnA16Changing(System.Nullable<bool> value);
    partial void OnA16Changed();
    partial void OnA16DChanging(string value);
    partial void OnA16DChanged();
    partial void OnA17Changing(System.Nullable<bool> value);
    partial void OnA17Changed();
    partial void OnA17DChanging(string value);
    partial void OnA17DChanged();
    partial void OnA18Changing(System.Nullable<bool> value);
    partial void OnA18Changed();
    partial void OnA18DChanging(string value);
    partial void OnA18DChanged();
    partial void OnA19Changing(System.Nullable<bool> value);
    partial void OnA19Changed();
    partial void OnA20Changing(System.Nullable<bool> value);
    partial void OnA20Changed();
    partial void OnA21Changing(System.Nullable<bool> value);
    partial void OnA21Changed();
    partial void OnA21DChanging(string value);
    partial void OnA21DChanged();
    partial void OnA22Changing(System.Nullable<bool> value);
    partial void OnA22Changed();
    partial void OnA22DChanging(string value);
    partial void OnA22DChanged();
    partial void OnA23Changing(System.Nullable<bool> value);
    partial void OnA23Changed();
    partial void OnA23DChanging(string value);
    partial void OnA23DChanged();
    partial void OnA24Changing(System.Nullable<bool> value);
    partial void OnA24Changed();
    partial void OnA24DChanging(string value);
    partial void OnA24DChanged();
    partial void OnA25Changing(string value);
    partial void OnA25Changed();
    partial void OnA26Changing(System.Nullable<bool> value);
    partial void OnA26Changed();
    partial void OnA26DChanging(string value);
    partial void OnA26DChanged();
    partial void OnA27Changing(string value);
    partial void OnA27Changed();
    partial void OnA28Changing(System.Nullable<bool> value);
    partial void OnA28Changed();
    partial void OnA28DChanging(string value);
    partial void OnA28DChanged();
    partial void OnA29Changing(string value);
    partial void OnA29Changed();
    partial void OnA30Changing(string value);
    partial void OnA30Changed();
    partial void OnA31Changing(string value);
    partial void OnA31Changed();
    partial void OnA32Changing(System.Nullable<bool> value);
    partial void OnA32Changed();
    partial void OnA33Changing(string value);
    partial void OnA33Changed();
    partial void OnA34Changing(string value);
    partial void OnA34Changed();
    partial void OnA35Changing(string value);
    partial void OnA35Changed();
    partial void OnA36Changing(string value);
    partial void OnA36Changed();
    partial void OnA37Changing(System.Nullable<bool> value);
    partial void OnA37Changed();
    partial void OnA38Changing(System.Nullable<bool> value);
    partial void OnA38Changed();
    partial void OnA39Changing(System.Nullable<bool> value);
    partial void OnA39Changed();
    partial void OnA39DChanging(string value);
    partial void OnA39DChanged();
    partial void OnA41Changing(System.Nullable<bool> value);
    partial void OnA41Changed();
    partial void OnA42Changing(string value);
    partial void OnA42Changed();
    partial void OnA43Changing(string value);
    partial void OnA43Changed();
    partial void OnA44Changing(string value);
    partial void OnA44Changed();
    partial void OnA45Changing(string value);
    partial void OnA45Changed();
    partial void OnA46Changing(string value);
    partial void OnA46Changed();
    partial void OnstudentIdChanging(string value);
    partial void OnstudentIdChanged();
    #endregion
		
		public QA()
		{
			this._student = default(EntityRef<student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="Bit")]
		public System.Nullable<bool> A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this.OnA1Changing(value);
					this.SendPropertyChanging();
					this._A1 = value;
					this.SendPropertyChanged("A1");
					this.OnA1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1D", DbType="NVarChar(255)")]
		public string A1D
		{
			get
			{
				return this._A1D;
			}
			set
			{
				if ((this._A1D != value))
				{
					this.OnA1DChanging(value);
					this.SendPropertyChanging();
					this._A1D = value;
					this.SendPropertyChanged("A1D");
					this.OnA1DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="Bit")]
		public System.Nullable<bool> A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this.OnA2Changing(value);
					this.SendPropertyChanging();
					this._A2 = value;
					this.SendPropertyChanged("A2");
					this.OnA2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2D", DbType="NVarChar(255)")]
		public string A2D
		{
			get
			{
				return this._A2D;
			}
			set
			{
				if ((this._A2D != value))
				{
					this.OnA2DChanging(value);
					this.SendPropertyChanging();
					this._A2D = value;
					this.SendPropertyChanged("A2D");
					this.OnA2DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="NVarChar(255)")]
		public string A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this.OnA3Changing(value);
					this.SendPropertyChanging();
					this._A3 = value;
					this.SendPropertyChanged("A3");
					this.OnA3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A4", DbType="Bit")]
		public System.Nullable<bool> A4
		{
			get
			{
				return this._A4;
			}
			set
			{
				if ((this._A4 != value))
				{
					this.OnA4Changing(value);
					this.SendPropertyChanging();
					this._A4 = value;
					this.SendPropertyChanged("A4");
					this.OnA4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A5", DbType="Bit")]
		public System.Nullable<bool> A5
		{
			get
			{
				return this._A5;
			}
			set
			{
				if ((this._A5 != value))
				{
					this.OnA5Changing(value);
					this.SendPropertyChanging();
					this._A5 = value;
					this.SendPropertyChanged("A5");
					this.OnA5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A5D", DbType="NVarChar(255)")]
		public string A5D
		{
			get
			{
				return this._A5D;
			}
			set
			{
				if ((this._A5D != value))
				{
					this.OnA5DChanging(value);
					this.SendPropertyChanging();
					this._A5D = value;
					this.SendPropertyChanged("A5D");
					this.OnA5DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A6", DbType="Bit")]
		public System.Nullable<bool> A6
		{
			get
			{
				return this._A6;
			}
			set
			{
				if ((this._A6 != value))
				{
					this.OnA6Changing(value);
					this.SendPropertyChanging();
					this._A6 = value;
					this.SendPropertyChanged("A6");
					this.OnA6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A7", DbType="Bit")]
		public System.Nullable<bool> A7
		{
			get
			{
				return this._A7;
			}
			set
			{
				if ((this._A7 != value))
				{
					this.OnA7Changing(value);
					this.SendPropertyChanging();
					this._A7 = value;
					this.SendPropertyChanged("A7");
					this.OnA7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A8", DbType="Bit")]
		public System.Nullable<bool> A8
		{
			get
			{
				return this._A8;
			}
			set
			{
				if ((this._A8 != value))
				{
					this.OnA8Changing(value);
					this.SendPropertyChanging();
					this._A8 = value;
					this.SendPropertyChanged("A8");
					this.OnA8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A8D", DbType="NVarChar(255)")]
		public string A8D
		{
			get
			{
				return this._A8D;
			}
			set
			{
				if ((this._A8D != value))
				{
					this.OnA8DChanging(value);
					this.SendPropertyChanging();
					this._A8D = value;
					this.SendPropertyChanged("A8D");
					this.OnA8DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A9", DbType="Bit")]
		public System.Nullable<bool> A9
		{
			get
			{
				return this._A9;
			}
			set
			{
				if ((this._A9 != value))
				{
					this.OnA9Changing(value);
					this.SendPropertyChanging();
					this._A9 = value;
					this.SendPropertyChanged("A9");
					this.OnA9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A9D", DbType="NVarChar(255)")]
		public string A9D
		{
			get
			{
				return this._A9D;
			}
			set
			{
				if ((this._A9D != value))
				{
					this.OnA9DChanging(value);
					this.SendPropertyChanging();
					this._A9D = value;
					this.SendPropertyChanged("A9D");
					this.OnA9DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A10", DbType="Bit")]
		public System.Nullable<bool> A10
		{
			get
			{
				return this._A10;
			}
			set
			{
				if ((this._A10 != value))
				{
					this.OnA10Changing(value);
					this.SendPropertyChanging();
					this._A10 = value;
					this.SendPropertyChanged("A10");
					this.OnA10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A11", DbType="Bit")]
		public System.Nullable<bool> A11
		{
			get
			{
				return this._A11;
			}
			set
			{
				if ((this._A11 != value))
				{
					this.OnA11Changing(value);
					this.SendPropertyChanging();
					this._A11 = value;
					this.SendPropertyChanged("A11");
					this.OnA11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A12", DbType="Bit")]
		public System.Nullable<bool> A12
		{
			get
			{
				return this._A12;
			}
			set
			{
				if ((this._A12 != value))
				{
					this.OnA12Changing(value);
					this.SendPropertyChanging();
					this._A12 = value;
					this.SendPropertyChanged("A12");
					this.OnA12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A13", DbType="Bit")]
		public System.Nullable<bool> A13
		{
			get
			{
				return this._A13;
			}
			set
			{
				if ((this._A13 != value))
				{
					this.OnA13Changing(value);
					this.SendPropertyChanging();
					this._A13 = value;
					this.SendPropertyChanged("A13");
					this.OnA13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A14", DbType="NVarChar(255)")]
		public string A14
		{
			get
			{
				return this._A14;
			}
			set
			{
				if ((this._A14 != value))
				{
					this.OnA14Changing(value);
					this.SendPropertyChanging();
					this._A14 = value;
					this.SendPropertyChanged("A14");
					this.OnA14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A15", DbType="Bit")]
		public System.Nullable<bool> A15
		{
			get
			{
				return this._A15;
			}
			set
			{
				if ((this._A15 != value))
				{
					this.OnA15Changing(value);
					this.SendPropertyChanging();
					this._A15 = value;
					this.SendPropertyChanged("A15");
					this.OnA15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A15D", DbType="NVarChar(255)")]
		public string A15D
		{
			get
			{
				return this._A15D;
			}
			set
			{
				if ((this._A15D != value))
				{
					this.OnA15DChanging(value);
					this.SendPropertyChanging();
					this._A15D = value;
					this.SendPropertyChanged("A15D");
					this.OnA15DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A16", DbType="Bit")]
		public System.Nullable<bool> A16
		{
			get
			{
				return this._A16;
			}
			set
			{
				if ((this._A16 != value))
				{
					this.OnA16Changing(value);
					this.SendPropertyChanging();
					this._A16 = value;
					this.SendPropertyChanged("A16");
					this.OnA16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A16D", DbType="NVarChar(255)")]
		public string A16D
		{
			get
			{
				return this._A16D;
			}
			set
			{
				if ((this._A16D != value))
				{
					this.OnA16DChanging(value);
					this.SendPropertyChanging();
					this._A16D = value;
					this.SendPropertyChanged("A16D");
					this.OnA16DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A17", DbType="Bit")]
		public System.Nullable<bool> A17
		{
			get
			{
				return this._A17;
			}
			set
			{
				if ((this._A17 != value))
				{
					this.OnA17Changing(value);
					this.SendPropertyChanging();
					this._A17 = value;
					this.SendPropertyChanged("A17");
					this.OnA17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A17D", DbType="NVarChar(255)")]
		public string A17D
		{
			get
			{
				return this._A17D;
			}
			set
			{
				if ((this._A17D != value))
				{
					this.OnA17DChanging(value);
					this.SendPropertyChanging();
					this._A17D = value;
					this.SendPropertyChanged("A17D");
					this.OnA17DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A18", DbType="Bit")]
		public System.Nullable<bool> A18
		{
			get
			{
				return this._A18;
			}
			set
			{
				if ((this._A18 != value))
				{
					this.OnA18Changing(value);
					this.SendPropertyChanging();
					this._A18 = value;
					this.SendPropertyChanged("A18");
					this.OnA18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A18D", DbType="NVarChar(255)")]
		public string A18D
		{
			get
			{
				return this._A18D;
			}
			set
			{
				if ((this._A18D != value))
				{
					this.OnA18DChanging(value);
					this.SendPropertyChanging();
					this._A18D = value;
					this.SendPropertyChanged("A18D");
					this.OnA18DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A19", DbType="Bit")]
		public System.Nullable<bool> A19
		{
			get
			{
				return this._A19;
			}
			set
			{
				if ((this._A19 != value))
				{
					this.OnA19Changing(value);
					this.SendPropertyChanging();
					this._A19 = value;
					this.SendPropertyChanged("A19");
					this.OnA19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A20", DbType="Bit")]
		public System.Nullable<bool> A20
		{
			get
			{
				return this._A20;
			}
			set
			{
				if ((this._A20 != value))
				{
					this.OnA20Changing(value);
					this.SendPropertyChanging();
					this._A20 = value;
					this.SendPropertyChanged("A20");
					this.OnA20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A21", DbType="Bit")]
		public System.Nullable<bool> A21
		{
			get
			{
				return this._A21;
			}
			set
			{
				if ((this._A21 != value))
				{
					this.OnA21Changing(value);
					this.SendPropertyChanging();
					this._A21 = value;
					this.SendPropertyChanged("A21");
					this.OnA21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A21D", DbType="NVarChar(255)")]
		public string A21D
		{
			get
			{
				return this._A21D;
			}
			set
			{
				if ((this._A21D != value))
				{
					this.OnA21DChanging(value);
					this.SendPropertyChanging();
					this._A21D = value;
					this.SendPropertyChanged("A21D");
					this.OnA21DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A22", DbType="Bit")]
		public System.Nullable<bool> A22
		{
			get
			{
				return this._A22;
			}
			set
			{
				if ((this._A22 != value))
				{
					this.OnA22Changing(value);
					this.SendPropertyChanging();
					this._A22 = value;
					this.SendPropertyChanged("A22");
					this.OnA22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A22D", DbType="NVarChar(255)")]
		public string A22D
		{
			get
			{
				return this._A22D;
			}
			set
			{
				if ((this._A22D != value))
				{
					this.OnA22DChanging(value);
					this.SendPropertyChanging();
					this._A22D = value;
					this.SendPropertyChanged("A22D");
					this.OnA22DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A23", DbType="Bit")]
		public System.Nullable<bool> A23
		{
			get
			{
				return this._A23;
			}
			set
			{
				if ((this._A23 != value))
				{
					this.OnA23Changing(value);
					this.SendPropertyChanging();
					this._A23 = value;
					this.SendPropertyChanged("A23");
					this.OnA23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A23D", DbType="NVarChar(255)")]
		public string A23D
		{
			get
			{
				return this._A23D;
			}
			set
			{
				if ((this._A23D != value))
				{
					this.OnA23DChanging(value);
					this.SendPropertyChanging();
					this._A23D = value;
					this.SendPropertyChanged("A23D");
					this.OnA23DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A24", DbType="Bit")]
		public System.Nullable<bool> A24
		{
			get
			{
				return this._A24;
			}
			set
			{
				if ((this._A24 != value))
				{
					this.OnA24Changing(value);
					this.SendPropertyChanging();
					this._A24 = value;
					this.SendPropertyChanged("A24");
					this.OnA24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A24D", DbType="NVarChar(255)")]
		public string A24D
		{
			get
			{
				return this._A24D;
			}
			set
			{
				if ((this._A24D != value))
				{
					this.OnA24DChanging(value);
					this.SendPropertyChanging();
					this._A24D = value;
					this.SendPropertyChanged("A24D");
					this.OnA24DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A25", DbType="NVarChar(255)")]
		public string A25
		{
			get
			{
				return this._A25;
			}
			set
			{
				if ((this._A25 != value))
				{
					this.OnA25Changing(value);
					this.SendPropertyChanging();
					this._A25 = value;
					this.SendPropertyChanged("A25");
					this.OnA25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A26", DbType="Bit")]
		public System.Nullable<bool> A26
		{
			get
			{
				return this._A26;
			}
			set
			{
				if ((this._A26 != value))
				{
					this.OnA26Changing(value);
					this.SendPropertyChanging();
					this._A26 = value;
					this.SendPropertyChanged("A26");
					this.OnA26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A26D", DbType="NVarChar(255)")]
		public string A26D
		{
			get
			{
				return this._A26D;
			}
			set
			{
				if ((this._A26D != value))
				{
					this.OnA26DChanging(value);
					this.SendPropertyChanging();
					this._A26D = value;
					this.SendPropertyChanged("A26D");
					this.OnA26DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A27", DbType="NVarChar(255)")]
		public string A27
		{
			get
			{
				return this._A27;
			}
			set
			{
				if ((this._A27 != value))
				{
					this.OnA27Changing(value);
					this.SendPropertyChanging();
					this._A27 = value;
					this.SendPropertyChanged("A27");
					this.OnA27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A28", DbType="Bit")]
		public System.Nullable<bool> A28
		{
			get
			{
				return this._A28;
			}
			set
			{
				if ((this._A28 != value))
				{
					this.OnA28Changing(value);
					this.SendPropertyChanging();
					this._A28 = value;
					this.SendPropertyChanged("A28");
					this.OnA28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A28D", DbType="NVarChar(255)")]
		public string A28D
		{
			get
			{
				return this._A28D;
			}
			set
			{
				if ((this._A28D != value))
				{
					this.OnA28DChanging(value);
					this.SendPropertyChanging();
					this._A28D = value;
					this.SendPropertyChanged("A28D");
					this.OnA28DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A29", DbType="NVarChar(255)")]
		public string A29
		{
			get
			{
				return this._A29;
			}
			set
			{
				if ((this._A29 != value))
				{
					this.OnA29Changing(value);
					this.SendPropertyChanging();
					this._A29 = value;
					this.SendPropertyChanged("A29");
					this.OnA29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A30", DbType="NVarChar(255)")]
		public string A30
		{
			get
			{
				return this._A30;
			}
			set
			{
				if ((this._A30 != value))
				{
					this.OnA30Changing(value);
					this.SendPropertyChanging();
					this._A30 = value;
					this.SendPropertyChanged("A30");
					this.OnA30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A31", DbType="NVarChar(255)")]
		public string A31
		{
			get
			{
				return this._A31;
			}
			set
			{
				if ((this._A31 != value))
				{
					this.OnA31Changing(value);
					this.SendPropertyChanging();
					this._A31 = value;
					this.SendPropertyChanged("A31");
					this.OnA31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A32", DbType="Bit")]
		public System.Nullable<bool> A32
		{
			get
			{
				return this._A32;
			}
			set
			{
				if ((this._A32 != value))
				{
					this.OnA32Changing(value);
					this.SendPropertyChanging();
					this._A32 = value;
					this.SendPropertyChanged("A32");
					this.OnA32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A33", DbType="NVarChar(255)")]
		public string A33
		{
			get
			{
				return this._A33;
			}
			set
			{
				if ((this._A33 != value))
				{
					this.OnA33Changing(value);
					this.SendPropertyChanging();
					this._A33 = value;
					this.SendPropertyChanged("A33");
					this.OnA33Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A34", DbType="NVarChar(255)")]
		public string A34
		{
			get
			{
				return this._A34;
			}
			set
			{
				if ((this._A34 != value))
				{
					this.OnA34Changing(value);
					this.SendPropertyChanging();
					this._A34 = value;
					this.SendPropertyChanged("A34");
					this.OnA34Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A35", DbType="NVarChar(255)")]
		public string A35
		{
			get
			{
				return this._A35;
			}
			set
			{
				if ((this._A35 != value))
				{
					this.OnA35Changing(value);
					this.SendPropertyChanging();
					this._A35 = value;
					this.SendPropertyChanged("A35");
					this.OnA35Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A36", DbType="NVarChar(255)")]
		public string A36
		{
			get
			{
				return this._A36;
			}
			set
			{
				if ((this._A36 != value))
				{
					this.OnA36Changing(value);
					this.SendPropertyChanging();
					this._A36 = value;
					this.SendPropertyChanged("A36");
					this.OnA36Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A37", DbType="Bit")]
		public System.Nullable<bool> A37
		{
			get
			{
				return this._A37;
			}
			set
			{
				if ((this._A37 != value))
				{
					this.OnA37Changing(value);
					this.SendPropertyChanging();
					this._A37 = value;
					this.SendPropertyChanged("A37");
					this.OnA37Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A38", DbType="Bit")]
		public System.Nullable<bool> A38
		{
			get
			{
				return this._A38;
			}
			set
			{
				if ((this._A38 != value))
				{
					this.OnA38Changing(value);
					this.SendPropertyChanging();
					this._A38 = value;
					this.SendPropertyChanged("A38");
					this.OnA38Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A39", DbType="Bit")]
		public System.Nullable<bool> A39
		{
			get
			{
				return this._A39;
			}
			set
			{
				if ((this._A39 != value))
				{
					this.OnA39Changing(value);
					this.SendPropertyChanging();
					this._A39 = value;
					this.SendPropertyChanged("A39");
					this.OnA39Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A39D", DbType="NVarChar(255)")]
		public string A39D
		{
			get
			{
				return this._A39D;
			}
			set
			{
				if ((this._A39D != value))
				{
					this.OnA39DChanging(value);
					this.SendPropertyChanging();
					this._A39D = value;
					this.SendPropertyChanged("A39D");
					this.OnA39DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A41", DbType="Bit")]
		public System.Nullable<bool> A41
		{
			get
			{
				return this._A41;
			}
			set
			{
				if ((this._A41 != value))
				{
					this.OnA41Changing(value);
					this.SendPropertyChanging();
					this._A41 = value;
					this.SendPropertyChanged("A41");
					this.OnA41Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A42", DbType="NVarChar(255)")]
		public string A42
		{
			get
			{
				return this._A42;
			}
			set
			{
				if ((this._A42 != value))
				{
					this.OnA42Changing(value);
					this.SendPropertyChanging();
					this._A42 = value;
					this.SendPropertyChanged("A42");
					this.OnA42Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A43", DbType="NVarChar(255)")]
		public string A43
		{
			get
			{
				return this._A43;
			}
			set
			{
				if ((this._A43 != value))
				{
					this.OnA43Changing(value);
					this.SendPropertyChanging();
					this._A43 = value;
					this.SendPropertyChanged("A43");
					this.OnA43Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A44", DbType="NVarChar(255)")]
		public string A44
		{
			get
			{
				return this._A44;
			}
			set
			{
				if ((this._A44 != value))
				{
					this.OnA44Changing(value);
					this.SendPropertyChanging();
					this._A44 = value;
					this.SendPropertyChanged("A44");
					this.OnA44Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A45", DbType="NVarChar(255)")]
		public string A45
		{
			get
			{
				return this._A45;
			}
			set
			{
				if ((this._A45 != value))
				{
					this.OnA45Changing(value);
					this.SendPropertyChanging();
					this._A45 = value;
					this.SendPropertyChanged("A45");
					this.OnA45Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A46", DbType="NVarChar(255)")]
		public string A46
		{
			get
			{
				return this._A46;
			}
			set
			{
				if ((this._A46 != value))
				{
					this.OnA46Changing(value);
					this.SendPropertyChanging();
					this._A46 = value;
					this.SendPropertyChanged("A46");
					this.OnA46Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentId", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string studentId
		{
			get
			{
				return this._studentId;
			}
			set
			{
				if ((this._studentId != value))
				{
					if (this._student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIdChanging(value);
					this.SendPropertyChanging();
					this._studentId = value;
					this.SendPropertyChanged("studentId");
					this.OnstudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="student_QA", Storage="_student", ThisKey="studentId", OtherKey="Id", IsForeignKey=true)]
		public student student
		{
			get
			{
				return this._student.Entity;
			}
			set
			{
				student previousValue = this._student.Entity;
				if (((previousValue != value) 
							|| (this._student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._student.Entity = null;
						previousValue.QAs.Remove(this);
					}
					this._student.Entity = value;
					if ((value != null))
					{
						value.QAs.Add(this);
						this._studentId = value.Id;
					}
					else
					{
						this._studentId = default(string);
					}
					this.SendPropertyChanged("student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.students")]
	public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.DateTime _date;
		
		private string _name;
		
		private string _gender;
		
		private System.DateTime _dob;
		
		private System.Nullable<int> _age;
		
		private string _nat;
		
		private string _nos;
		
		private string _orderrr;
		
		private string _address;
		
		private string _djob;
		
		private string _dedu;
		
		private string _daddress;
		
		private string _dtelephone;
		
		private string _dmobile;
		
		private string _mname;
		
		private string _mjob;
		
		private string _medu;
		
		private string _maddress;
		
		private string _mmobile;
		
		private System.Nullable<bool> _withdad;
		
		private System.Nullable<bool> _withmom;
		
		private System.Nullable<bool> _withother;
		
		private string _whocare;
		
		private string _problem;
		
		private EntitySet<QA> _QAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void OnnatChanging(string value);
    partial void OnnatChanged();
    partial void OnnosChanging(string value);
    partial void OnnosChanged();
    partial void OnorderrrChanging(string value);
    partial void OnorderrrChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OndjobChanging(string value);
    partial void OndjobChanged();
    partial void OndeduChanging(string value);
    partial void OndeduChanged();
    partial void OndaddressChanging(string value);
    partial void OndaddressChanged();
    partial void OndtelephoneChanging(string value);
    partial void OndtelephoneChanged();
    partial void OndmobileChanging(string value);
    partial void OndmobileChanged();
    partial void OnmnameChanging(string value);
    partial void OnmnameChanged();
    partial void OnmjobChanging(string value);
    partial void OnmjobChanged();
    partial void OnmeduChanging(string value);
    partial void OnmeduChanged();
    partial void OnmaddressChanging(string value);
    partial void OnmaddressChanged();
    partial void OnmmobileChanging(string value);
    partial void OnmmobileChanged();
    partial void OnwithdadChanging(System.Nullable<bool> value);
    partial void OnwithdadChanged();
    partial void OnwithmomChanging(System.Nullable<bool> value);
    partial void OnwithmomChanged();
    partial void OnwithotherChanging(System.Nullable<bool> value);
    partial void OnwithotherChanged();
    partial void OnwhocareChanging(string value);
    partial void OnwhocareChanged();
    partial void OnproblemChanging(string value);
    partial void OnproblemChanged();
    #endregion
		
		public student()
		{
			this._QAs = new EntitySet<QA>(new Action<QA>(this.attach_QAs), new Action<QA>(this.detach_QAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nat
		{
			get
			{
				return this._nat;
			}
			set
			{
				if ((this._nat != value))
				{
					this.OnnatChanging(value);
					this.SendPropertyChanging();
					this._nat = value;
					this.SendPropertyChanged("nat");
					this.OnnatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nos", DbType="NVarChar(50)")]
		public string nos
		{
			get
			{
				return this._nos;
			}
			set
			{
				if ((this._nos != value))
				{
					this.OnnosChanging(value);
					this.SendPropertyChanging();
					this._nos = value;
					this.SendPropertyChanged("nos");
					this.OnnosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderrr", DbType="NVarChar(50)")]
		public string orderrr
		{
			get
			{
				return this._orderrr;
			}
			set
			{
				if ((this._orderrr != value))
				{
					this.OnorderrrChanging(value);
					this.SendPropertyChanging();
					this._orderrr = value;
					this.SendPropertyChanged("orderrr");
					this.OnorderrrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_djob", DbType="NVarChar(50)")]
		public string djob
		{
			get
			{
				return this._djob;
			}
			set
			{
				if ((this._djob != value))
				{
					this.OndjobChanging(value);
					this.SendPropertyChanging();
					this._djob = value;
					this.SendPropertyChanged("djob");
					this.OndjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dedu", DbType="NVarChar(50)")]
		public string dedu
		{
			get
			{
				return this._dedu;
			}
			set
			{
				if ((this._dedu != value))
				{
					this.OndeduChanging(value);
					this.SendPropertyChanging();
					this._dedu = value;
					this.SendPropertyChanged("dedu");
					this.OndeduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daddress", DbType="NVarChar(100)")]
		public string daddress
		{
			get
			{
				return this._daddress;
			}
			set
			{
				if ((this._daddress != value))
				{
					this.OndaddressChanging(value);
					this.SendPropertyChanging();
					this._daddress = value;
					this.SendPropertyChanged("daddress");
					this.OndaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtelephone", DbType="NVarChar(50)")]
		public string dtelephone
		{
			get
			{
				return this._dtelephone;
			}
			set
			{
				if ((this._dtelephone != value))
				{
					this.OndtelephoneChanging(value);
					this.SendPropertyChanging();
					this._dtelephone = value;
					this.SendPropertyChanged("dtelephone");
					this.OndtelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dmobile", DbType="NVarChar(50)")]
		public string dmobile
		{
			get
			{
				return this._dmobile;
			}
			set
			{
				if ((this._dmobile != value))
				{
					this.OndmobileChanging(value);
					this.SendPropertyChanging();
					this._dmobile = value;
					this.SendPropertyChanged("dmobile");
					this.OndmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mname", DbType="NVarChar(50)")]
		public string mname
		{
			get
			{
				return this._mname;
			}
			set
			{
				if ((this._mname != value))
				{
					this.OnmnameChanging(value);
					this.SendPropertyChanging();
					this._mname = value;
					this.SendPropertyChanged("mname");
					this.OnmnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mjob", DbType="NVarChar(50)")]
		public string mjob
		{
			get
			{
				return this._mjob;
			}
			set
			{
				if ((this._mjob != value))
				{
					this.OnmjobChanging(value);
					this.SendPropertyChanging();
					this._mjob = value;
					this.SendPropertyChanged("mjob");
					this.OnmjobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medu", DbType="NVarChar(50)")]
		public string medu
		{
			get
			{
				return this._medu;
			}
			set
			{
				if ((this._medu != value))
				{
					this.OnmeduChanging(value);
					this.SendPropertyChanging();
					this._medu = value;
					this.SendPropertyChanged("medu");
					this.OnmeduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maddress", DbType="NVarChar(100)")]
		public string maddress
		{
			get
			{
				return this._maddress;
			}
			set
			{
				if ((this._maddress != value))
				{
					this.OnmaddressChanging(value);
					this.SendPropertyChanging();
					this._maddress = value;
					this.SendPropertyChanged("maddress");
					this.OnmaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mmobile", DbType="NVarChar(50)")]
		public string mmobile
		{
			get
			{
				return this._mmobile;
			}
			set
			{
				if ((this._mmobile != value))
				{
					this.OnmmobileChanging(value);
					this.SendPropertyChanging();
					this._mmobile = value;
					this.SendPropertyChanged("mmobile");
					this.OnmmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withdad", DbType="Bit")]
		public System.Nullable<bool> withdad
		{
			get
			{
				return this._withdad;
			}
			set
			{
				if ((this._withdad != value))
				{
					this.OnwithdadChanging(value);
					this.SendPropertyChanging();
					this._withdad = value;
					this.SendPropertyChanged("withdad");
					this.OnwithdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withmom", DbType="Bit")]
		public System.Nullable<bool> withmom
		{
			get
			{
				return this._withmom;
			}
			set
			{
				if ((this._withmom != value))
				{
					this.OnwithmomChanging(value);
					this.SendPropertyChanging();
					this._withmom = value;
					this.SendPropertyChanged("withmom");
					this.OnwithmomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_withother", DbType="Bit")]
		public System.Nullable<bool> withother
		{
			get
			{
				return this._withother;
			}
			set
			{
				if ((this._withother != value))
				{
					this.OnwithotherChanging(value);
					this.SendPropertyChanging();
					this._withother = value;
					this.SendPropertyChanged("withother");
					this.OnwithotherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whocare", DbType="NVarChar(50)")]
		public string whocare
		{
			get
			{
				return this._whocare;
			}
			set
			{
				if ((this._whocare != value))
				{
					this.OnwhocareChanging(value);
					this.SendPropertyChanging();
					this._whocare = value;
					this.SendPropertyChanged("whocare");
					this.OnwhocareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_problem", DbType="NVarChar(50)")]
		public string problem
		{
			get
			{
				return this._problem;
			}
			set
			{
				if ((this._problem != value))
				{
					this.OnproblemChanging(value);
					this.SendPropertyChanging();
					this._problem = value;
					this.SendPropertyChanged("problem");
					this.OnproblemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="student_QA", Storage="_QAs", ThisKey="Id", OtherKey="studentId")]
		public EntitySet<QA> QAs
		{
			get
			{
				return this._QAs;
			}
			set
			{
				this._QAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QAs(QA entity)
		{
			this.SendPropertyChanging();
			entity.student = this;
		}
		
		private void detach_QAs(QA entity)
		{
			this.SendPropertyChanging();
			entity.student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _username;
		
		private string _password;
		
		private System.Data.Linq.Binary _profile_image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onprofile_imageChanging(System.Data.Linq.Binary value);
    partial void Onprofile_imageChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_image", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary profile_image
		{
			get
			{
				return this._profile_image;
			}
			set
			{
				if ((this._profile_image != value))
				{
					this.Onprofile_imageChanging(value);
					this.SendPropertyChanging();
					this._profile_image = value;
					this.SendPropertyChanged("profile_image");
					this.Onprofile_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
