//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string QAnswer { get; set; }
        public string SubQuestion { get; set; }
        public string SQAnswer { get; set; }
        public string studentId { get; set; }
    
        public virtual student student { get; set; }
    }
}
