//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class son
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public son()
        {
            this.QAs = new HashSet<QA>();
        }
    
        public string Id { get; set; }
        public string date { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string age { get; set; }
        public string nat { get; set; }
        public string nos { get; set; }
        public string orderrr { get; set; }
        public string address { get; set; }
        public string djob { get; set; }
        public string dedu { get; set; }
        public string daddress { get; set; }
        public string dtelephone { get; set; }
        public string dmobile { get; set; }
        public string mname { get; set; }
        public string mjob { get; set; }
        public string medu { get; set; }
        public string maddress { get; set; }
        public string mmobile { get; set; }
        public Nullable<bool> withdad { get; set; }
        public Nullable<bool> withmom { get; set; }
        public Nullable<bool> withother { get; set; }
        public string whocare { get; set; }
        public string problem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QA> QAs { get; set; }
    }
}
